[
    {
        "created_at": "2025-05-06T10:19:00.674483",
        "forwarded_at": "2025-05-06T10:19:00.674559",
        "id": 1,
        "message": "MSH|^~\\&|TESTSYSTEM|LAB|MIRTH|||20250428||ORU^R01|123456|P|2.4\r\nPID|||12345||DOE^JOHN\r\nOBR|1||67890|TEST^Test^L|||202504281000\r\nOBX|1|NM|^Test Result||42|IU/L\r\n",
        "response": "HTTPConnectionPool(host='172.22.192.1', port=9000): Max retries exceeded with url: /forwarder/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb538bd7fb0>, 'Connection to 172.22.192.1 timed out. (connect timeout=None)'))",
        "response_code": null,
        "status": "error"
    }
]